

Import('env')

lib_src = ['SmokeSystem.cpp','SourceManager.cpp']
lib_target = 'solver'

env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')

lib = env.StaticLibrary(source = lib_src , target = lib_target)
