

Import('env')

lib_src = [
			'SOP_Smoke_Source.cpp',
			'SOP_OpenVDB_HelloWorld.cpp'
			]


for file in lib_src:
	lib_target = file.rstrip('.cpp')
	lib = env.SharedLibrary(source = file , target = lib_target)