Import('env')

houdini_utils_env = env.Clone()
houdini_adapters_env = env.Clone()
houdini_plugins_env = env.Clone()

SConscript('utils/SConscript', exports={'env':houdini_utils_env})
SConscript('adapters/SConscript', exports={'env':houdini_adapters_env})
SConscript('plugins/SConscript', exports={'env':houdini_plugins_env})