Import('env')

env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')

core_env = env.Clone()
SConscript('core/SConscript', exports={'env':core_env})

sources_env = env.Clone()
SConscript('sources/SConscript', exports={'env':sources_env})


solver_env = env.Clone()
SConscript('solver/SConscript', exports={'env':solver_env})
