
env = Environment(CCFLAGS = ['-O2','-DRENDER_INFO','-std=c++11'])
env.Replace(CXX = "g++-4.8")

#env.Replace(CXXCOMSTR = "Compiling $TARGET")
#env.Replace(SHCXXCOMSTR = "Compiling $TARGET")
#env.Replace(CCCOMSTR = "Compiling $TARGET")
#env.Replace(SHCCCOMSTR = "Compiling $TARGET")
#env.Replace(LINKCOMSTR = "Linking $TARGET")
#env.Replace(SHLINKCOMSTR = "Linking $TARGET")

env['ROOT'] = '/home/user/git/nimble/nimble'
env['SMOKE_ROOT'] = env['ROOT'] + '/smoke' 
env['SMOKE_HOUDINI'] = env['SMOKE_ROOT'] + '/houdini'
env['SMOKE_LIB'] = env['SMOKE_ROOT'] + '/smoke'

print env['ROOT']
print env['SMOKE_ROOT']
print env['SMOKE_HOUDINI']
print env['SMOKE_LIB']

env.Append(CCFLAGS=['-I'+env['ROOT']])
env.Append(CCFLAGS=['-isystem','/opt/houdini/toolkit/include'])

SConscript('smoke/SConscript', variant_dir='debug', exports={'env':env})