

Import('env')

lib_src = [
			'AddSourceAdapter.cpp',
			'SolveSimAdapter.cpp'
			]
lib_target = 'houdini_adapters'

env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')


lib = env.StaticLibrary(source = lib_src , target = lib_target)
